# Generated by Django 3.0.7 on 2020-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_auto_20200606_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('degree_type', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('descriptions', models.ManyToManyField(to='me.School_Description')),
            ],
        ),
    ]
