# Generated by Django 3.0.7 on 2020-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_school_school_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Database', 'Database'), ('Integrated Development Environment/Text Editor', 'Integrated Development Environment/Text Editor'), ('Report/Analytics', 'Report/Analytics')], max_length=100)),
                ('skill_subtype', models.CharField(choices=[('Proficient', 'Proficient'), ('Knowledge of', 'Knowledge of')], max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Job_Responsibility',
            new_name='JobResponsibility',
        ),
        migrations.RenameModel(
            old_name='School_Description',
            new_name='SchoolDescription',
        ),
    ]
