# Generated by Django 3.0.7 on 2020-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_auto_20200606_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('Programming Language', 'Programming Language'), ('Database', 'Database'), ('Integrated Development Environment/Text Editor', 'Integrated Development Environment/Text Editor'), ('Report/Analytics', 'Report/Analytics')], default='NA', max_length=100, null=True),
        ),
    ]
