# Generated by Django 3.0.7 on 2020-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_auto_20200606_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_subtype',
            field=models.CharField(blank=True, choices=[('Proficient', 'Proficient'), ('Knowledge of', 'Knowledge of')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Database', 'Database'), ('Integrated Development Environment/Text Editor', 'Integrated Development Environment/Text Editor'), ('Report/Analytics', 'Report/Analytics')], default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
