# Generated by Django 3.0.7 on 2020-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_auto_20200606_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Database', 'Database'), ('Integrated Development Environment/Text Editor', 'Integrated Development Environment/Text Editor'), ('Report/Analytics', 'Report/Analytics'), ('ETL', 'ETL')], max_length=100),
        ),
    ]
