# Generated by Django 3.0.7 on 2020-06-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0010_auto_20200606_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.ImageField(height_field=300, upload_to='', width_field=200)),
            ],
        ),
    ]
