# Generated by Django 3.0.7 on 2020-06-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0011_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Personal', 'Personal')], default='Professional', max_length=20),
            preserve_default=False,
        ),
    ]
