# Generated by Django 3.0.7 on 2020-06-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
