# Generated by Django 3.0.7 on 2020-06-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0013_auto_20200607_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
