# Generated by Django 3.0.7 on 2020-06-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0014_auto_20200607_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
